version: '3'

volumes:
  logs:
  api:

services:

  api:
    build: .
    env_file: .env
    environment:
      - TZ=Asia/Almaty
    ports:
      - ${PORT}:8000
    command: uvicorn --host 0.0.0.0 api.app:app

# TODO: запускать под gunicorn